name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests
        run: |
          make test

      - name: Codecov
        uses: codecov/codecov-action@v2

      - name: Benchmark
        run: |
          make bench

      - name: Shor
        run: |
          make shor
